name: Build & Deploy to Azure Web App (VAISDAY4TARGET)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  APP_NAME: VAISDAY4TARGET        # <- exact Web App name
  ZIP_NAME: release.zip
  NODE_VERSION: 22.x

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read              # checkout

    steps:
      # ---- Pull repo ----
      - name: Checkout code
        uses: actions/checkout@v4

      # ---- Node toolchain (only matters if you later add package.json) ----
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      # ---- Optional install / build / test ----
      # Will be skipped gracefully if no package.json exists.
      - name: npm install / build / test (if present)
        run: |
          if [ -f package.json ]; then
            echo "package.json found – running npm install/build/test"
            npm install
            npm run build --if-present
            npm run test  --if-present
          else
            echo "No package.json – treating repo as static content"
          fi

      # ---- Package everything into a zip ----
      - name: Zip site for deployment
        run: zip -r ${{ env.ZIP_NAME }} . -x ".git/*" -x ".github/*"

      # ---- Upload artefact for the deploy job ----
      - name: Upload artefact
        uses: actions/upload-artifact@v4
        with:
          name: site-package
          path: ${{ env.ZIP_NAME }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read               # download artefact

    steps:
      # ---- Get artefact from build job ----
      - name: Download artefact
        uses: actions/download-artifact@v4
        with:
          name: site-package

      # ---- Deploy with publish profile (no AAD/OIDC hassles) ----
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name:     ${{ env.APP_NAME }}
          package:      ${{ env.ZIP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
